// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Hello implements hello operation.
//
// Hello👋.
//
// GET /hello
func (UnimplementedHandler) Hello(ctx context.Context) (r *Hello, _ error) {
	return r, ht.ErrNotImplemented
}

// HelloBearer implements helloBearer operation.
//
// Hello bearer security schema👋.
//
// GET /hello-bearer
func (UnimplementedHandler) HelloBearer(ctx context.Context) (r *Hello, _ error) {
	return r, ht.ErrNotImplemented
}

// HelloOAuth2 implements helloOAuth2 operation.
//
// Hello oauth 2.0 security schema👋.
//
// GET /hello-oauth2
func (UnimplementedHandler) HelloOAuth2(ctx context.Context) (r *Hello, _ error) {
	return r, ht.ErrNotImplemented
}

// HelloOIDC implements helloOIDC operation.
//
// Hello openid connect security schema👋.
//
// GET /hello-oidc
func (UnimplementedHandler) HelloOIDC(ctx context.Context) (r *Hello, _ error) {
	return r, ht.ErrNotImplemented
}
