// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * openapi 3.0 auth code generator sample
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package openapi

import (
	"net/http"
	"strings"
)

// Summer2024APIController binds http requests to an api service and writes the service results to the http response
type Summer2024APIController struct {
	service      Summer2024APIServicer
	errorHandler ErrorHandler
}

// Summer2024APIOption for how the controller is set up.
type Summer2024APIOption func(*Summer2024APIController)

// WithSummer2024APIErrorHandler inject ErrorHandler into controller
func WithSummer2024APIErrorHandler(h ErrorHandler) Summer2024APIOption {
	return func(c *Summer2024APIController) {
		c.errorHandler = h
	}
}

// NewSummer2024APIController creates a default api controller
func NewSummer2024APIController(s Summer2024APIServicer, opts ...Summer2024APIOption) *Summer2024APIController {
	controller := &Summer2024APIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the Summer2024APIController
func (c *Summer2024APIController) Routes() Routes {
	return Routes{
		"Hello": Route{
			strings.ToUpper("Get"),
			"/hello",
			c.Hello,
		},
		"HelloBearer": Route{
			strings.ToUpper("Get"),
			"/hello-bearer",
			c.HelloBearer,
		},
		"HelloOAuth2": Route{
			strings.ToUpper("Get"),
			"/hello-oauth2",
			c.HelloOAuth2,
		},
		"HelloOIDC": Route{
			strings.ToUpper("Get"),
			"/hello-oidc",
			c.HelloOIDC,
		},
	}
}

// Hello - hello👋
func (c *Summer2024APIController) Hello(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.Hello(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// HelloBearer - hello bearer👋
func (c *Summer2024APIController) HelloBearer(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.HelloBearer(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// HelloOAuth2 - hello oauth2👋
func (c *Summer2024APIController) HelloOAuth2(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.HelloOAuth2(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// HelloOIDC - hello openid connect👋
func (c *Summer2024APIController) HelloOIDC(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.HelloOIDC(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
